raw: 
  database: "SEC_FILINGS_DB"
  schema: "RAW_DATA"
  tables: 
    10_K_CHUNKS: 
      ID: 
        TYPE: "INTEGER"
      RELATIVE_PATH: 
        TYPE: "VARCHAR(16777216)" 
      SIZE: 
        TYPE: "NUMBER(38,0)"
      FILE_URL: 
        TYPE: "VARCHAR(16777216)"
      SCOPED_FILE_URL: 
        TYPE: "VARCHAR(16777216)" 
      CHUNK: 
        TYPE: "VARCHAR(16777216)"
      CATEGORY: 
        TYPE: "VARCHAR(16777216)"
      TICKER: 
        TYPE: "VARCHAR(16777216)"
      AS_OF_DATE: 
        TYPE: "VARCHAR(16777216)"
    COMPANIES_RAW: 
      RAW_JSON: 
        TYPE: "VARIANT"
    COMPANIES:
      ID: 
        TYPE: "INTEGER" 
      CIK: 
        TYPE: "INTEGER"
      TICKER: 
        TYPE: "VARCHAR"
      TITLE: 
        TYPE: "VARCHAR"   
  stages: 
    10_K_FILINGS: 
      requires_sse: True
      is_directory: True
    UDFS: 
      requires_sse: False
      is_directory: False
    COMPANIES: 
      requires_sse: False
      is_directory: False
  udfs:
    chunk_text:
      source: "chunk_text.py" 
      declaration: >
        create or replace function chunk_text(text string)
        returns table (chunk varchar)
        language python
        runtime_version='3.9'
        packages = ('pandas','langchain')
        handler='chunk_text.chunk_text'
        imports=('@UDFS/chunk_text.py');
    read_text:
      source: "read_file.py"
      declaration: >
        create or replace function read_file(stage_path string)
        returns STRING
        language python
        runtime_version='3.9'
        packages = ('snowflake-snowpark-python')
        handler='read_file.read'
        imports=('@UDFS/read_file.py');
  sql_files: 
    - "companies_setup.sql"