snowflake:
  user: "mlake@continuus.ai"
  account: "CONTINUUSTECHNOLOGIES-DEVAZR"
  authenticator: "externalbrowser"
  warehouse: "BIDS_WH"
  role: "SNOWFLAKE-PI30485-DEVELOPER"
  database: "SEC_FILINGS_DB"
raw: 
  database: "SEC_FILINGS_DB"
  schema: "RAW_DATA"
  stage: "10_K_FILINGS"
  udfs:
    source: "rag_processing.py" 
    rag_processing: 
      declaration: >
        create or replace function chunk_text(text string)
        returns table (chunk varchar)
        language python
        runtime_version='3.9'
        packages = ('pandas','langchain')
        handler='rag_processing.chunk_text'
        imports=('@UDFS/rag_processing.py');
