USE SCHEMA "SEC_FILINGS_DB"."RAW_DATA";

COPY INTO COMPANIES_RAW
FROM @"COMPANIES"
FILE_FORMAT = (TYPE = 'JSON', STRIP_OUTER_ARRAY = FALSE);

CREATE OR REPLACE TABLE COMPANIES AS (
SELECT  SEQ4(1) + 1 AS ID, F.VALUE:cik_str::integer AS CIK, F.VALUE:ticker::varchar AS TICKER, F.VALUE:title::varchar AS TITLE
FROM COMPANIES_RAW C,
LATERAL FLATTEN(input => C.RAW_JSON) F
ORDER BY CIK
);