USE ROLE "SNOWFLAKE-LQ18747-DEVELOPER";

CREATE DATABASE IF NOT EXISTS SEC_FILINGS_DB;
CREATE SCHEMA IF NOT EXISTS SEC_FILINGS_DB.RAW_DATA;
CREATE SCHEMA IF NOT EXISTS SEC_FILINGS_DB.PROCESSED_DATA;
CREATE SCHEMA IF NOT EXISTS CORTEX_DEMOS.SEC_SEMANTIC_MODEL;

CREATE STAGE IF NOT EXISTS SEC_FILINGS_DB.RAW_DATA.10_K_FILINGS;
CREATE STAGE IF NOT EXISTS SEC_FILINGS_DB.RAW_DATA.10_K_METRICS;


