USE ROLE "SNOWFLAKE-LQ18747-DEVELOPER";

CREATE DATABASE IF NOT EXISTS CORTEX_DEMOS; 
CREATE SCHEMA IF NOT EXISTS CORTEX_DEMOS.SEC_SEMANTIC_MODEL;
CREATE STAGE IF NOT EXISTS CORTEX_DEMOS.SEC_FILINGS.10_K_STAGE;


